Morpheus "Apollo" gentx preparation
desmos-labs/morpheus pull request #273
Opened 2021-04-24 14:20 UTC by RiccardoM

2021-04-24 17:30 UTC, bragaz requested changes

2021-04-24 17:30 UTC, bragaz commented on morpheus-apollo-1/genesis.json
> +        {
remove from here to 481

2021-04-24 17:30 UTC, bragaz commented on morpheus-apollo-1/genesis.json
> +                  "moniker": "leobragaz",
remove this validator

2021-04-25 07:44 UTC, kwunyeung requested changes
I can successfully start a node if I move the genesis time to past time. The current 144 accounts and genesis txs are correct.

Let's update the `max_validators` to `150`.

2021-04-26 04:25 UTC, kwunyeung requested changes

2021-04-26 04:25 UTC, kwunyeung commented on morpheus-apollo-1/genesis.json
> +        }
Add bank balances for the vesting account
```suggestion
        },
        {
          "address": "desmos1snmetx9sfrmznr4z6d3lnwlyvwu36sgcpzzhlr",
          "coins": [
            {
              "denom": "udaric",
              "amount": "300000000000"
            }
          ]
        }
```

2021-04-26 04:25 UTC, kwunyeung commented on morpheus-apollo-1/genesis.json
> +        }
Add a new vesting account with vesting period
```suggestion
        },
        {
          "@type": "/cosmos.vesting.v1beta1.PeriodicVestingAccount",
          "base_vesting_account": {
            "base_account": {
              "address": "desmos1snmetx9sfrmznr4z6d3lnwlyvwu36sgcpzzhlr",
              "pub_key": null,
              "account_number": "0",
              "sequence": "0"
            },
            "original_vesting": [
              {
                "denom": "udaric",
                "amount": "30000000000"
              }
            ],
            "delegated_free": [],
            "delegated_vesting": [],
            "end_time": "1619766000"
          },
          "start_time": "1619506800",
          "vesting_periods": [
            {
              "length": "86400",
              "amount": [
                {
                  "denom": "udaric",
                  "amount": "10000000000"
                }
              ]
            },
            {
              "length": "86400",
              "amount": [
                {
                  "denom": "udaric",
                  "amount": "10000000000"
                }
              ]
            },
            {
              "length": "86400",
              "amount": [
                {
                  "denom": "udaric",
                  "amount": "10000000000"
                }
              ]
            }
          ]
        }
```

2021-04-26 05:18 UTC, RiccardoM commented on morpheus-apollo-1/genesis.json
> +        {
Done

2021-04-26 05:18 UTC, RiccardoM commented on morpheus-apollo-1/genesis.json
> +                  "moniker": "leobragaz",
Done

2021-04-26 08:28 UTC, bragaz approved these changes
🚀

2021-04-26 08:32 UTC, merged